pub mod affine;
pub mod atbash;
pub mod baconian;
pub mod caesar;
// pub mod homophonic;
pub mod morse;
// pub mod playfair;
// pub mod polybius_square;
pub mod rot13;
pub mod simple_sub;
// pub mod straddle_checkerboard;