pub mod autokey;
pub mod beaufort;
pub mod bellaso;
// pub mod chaocipher;
pub mod classic_vigenere;
// pub mod four_square;
pub mod keyed_vig;
// pub mod otp;
pub mod porta;
// pub mod running_key;
// pub mod two_square;